// =============================================================================
// riff/riffOffParity.test.mjs — 🎸 THE RIFF-OFF IS THE THING YOU PRACTISED
// -----------------------------------------------------------------------------
// Riff Practice exists so that when a duel starts, your hands already know the
// instrument. That promise is only true if the two highways ask for the SAME
// things: same tiers, same lead times, same grade windows, same gestures.
//
// This file is the guard on that promise. It fails if the practice highway and
// the riff-off drift apart — which they had, quietly and in three places:
//
//   1. The tier ladder was a hand-kept duplicate in arrowHighwayEngine.js.
//      It agreed by luck, and nothing made it keep agreeing.
//   2. `perf` — sustains, bends, note directions — was generated by the engine
//      for both sides of every duel and then never forwarded onto the overlay.
//      `riffStartRun` read `side.perf?.[i] ?? {}` and got `{}` every single
//      time, so riff-offs had no tails, no bends and no arrows while practice
//      had all three.
//   3. Two-note power chords were skipped in riff-offs outright.
//
// All three are fixed. This test is what stops them coming back.
//
// Run: node --import ../engine/testAssetStub.mjs src/riff/riffOffParity.test.mjs
// =============================================================================
import assert from 'node:assert/strict';

import { RIFF_FALL_DIFFICULTY, buildRiffTimeline } from './fallingNotes.js';
import { TIERS as PRACTICE_TIERS } from './arrowHighwayEngine.js';
import { PERFORMANCE_DEFAULTS } from './riffPerformance.js';
import { makeInitialState } from '../engine/state.js';
import { applyAction } from '../engine/reduce.js';
import { riffOffStarted, riffRound2Started } from '../engine/actions.js';

let checks = 0;
const ok = (cond, msg) => { checks++; assert.ok(cond, msg); };
const eq = (a, b, msg) => { checks++; assert.equal(a, b, msg); };

// ── 1. THE LADDER ────────────────────────────────────────────────────────────
// Same tiers, same lead times, same windows, same length caps, same label rule.
{
  assert.deepEqual(
    Object.keys(PRACTICE_TIERS), Object.keys(RIFF_FALL_DIFFICULTY),
    'practice and the riff-off offer the same difficulty tiers');

  for (const [id, duel] of Object.entries(RIFF_FALL_DIFFICULTY)) {
    const prac = PRACTICE_TIERS[id];
    eq(prac.leadTime, duel.leadTime, `${id}: same lead time`);
    eq(prac.perfect,  duel.perfect,  `${id}: same perfect window`);
    eq(prac.good,     duel.good,     `${id}: same good window`);
    eq(prac.ok,       duel.ok,       `${id}: same ok window`);
    eq(prac.maxLen,   duel.maxLen,   `${id}: same riff length cap`);
    eq(prac.showNums, duel.showLabels, `${id}: same read-the-lane rule`);
    // The ladder has to actually be a ladder — each tier drops faster and
    // judges tighter than the one below it.
    ok(duel.perfect < duel.good && duel.good < duel.ok, `${id}: windows nest`);
  }
  const order = ['rookie', 'gigging', 'shredder', 'virtuoso'];
  for (let i = 1; i < order.length; i++) {
    const lo = RIFF_FALL_DIFFICULTY[order[i - 1]], hi = RIFF_FALL_DIFFICULTY[order[i]];
    ok(hi.leadTime < lo.leadTime, `${order[i]} falls faster than ${order[i - 1]}`);
    ok(hi.ok       < lo.ok,       `${order[i]} judges tighter than ${order[i - 1]}`);
    ok(hi.maxLen   > lo.maxLen,   `${order[i]} charts more notes than ${order[i - 1]}`);
  }
}

// ── 2. THE CHART ─────────────────────────────────────────────────────────────
// Every duel, at every tier, must hand both performers a chart carrying the
// gestures practice teaches: a voiced string+fret per note, direction arrows,
// sustain tails, bends, and two-note chords.
const seen = { sustain: 0, bend: 0, chord: 0, up: 0, down: 0, same: 0, notes: 0, charts: 0 };
{
  const config = { spirits: [{ id: 'wildaxe', name: 'W' }, { id: 'vera', name: 'V' }] };

  const auditChart = (side, where) => {
    seen.charts++;
    const n = side.degrees.length;
    // Every index-keyed array grew together. `noteIdx` is the key results,
    // scoring, ghost letters and glitch indexes are ALL built against — if
    // these ever disagree, a player is scored against a gem they never saw.
    eq(side.sharps.length,  n, `${where}: sharps aligned`);
    eq(side.rhythm.length,  n, `${where}: rhythm aligned`);
    eq(side.perf.length,    n, `${where}: perf aligned`);
    eq(side.chordOf.length, n, `${where}: chordOf aligned`);

    side.perf.forEach((p, i) => {
      seen.notes++;
      // Voiced onto a real, reachable place on a real string.
      ok(Number.isInteger(p.string) && p.string >= 0 && p.string <= 5,
        `${where}[${i}]: on a string`);
      ok(Number.isInteger(p.fret) && p.fret >= 0 && p.fret <= 12,
        `${where}[${i}]: within the first position`);
      // Direction is NOTATION — the arrow the highway draws. Practice always
      // has one; so must a duel.
      ok(['up', 'down', 'same'].includes(p.dir), `${where}[${i}]: has a direction`);
      seen[p.dir]++;
      if (p.sustain > 0) seen.sustain++;
      if (p.bend) {
        seen.bend++;
        // A bend is a gesture ON a ringing note, at a marked moment in its
        // tail. One without a tail is unplayable by construction.
        ok(p.sustain > 0, `${where}[${i}]: bends only on sustains`);
        ok(['up', 'down'].includes(p.bendDir), `${where}[${i}]: bend has a direction`);
        ok(p.bendAmt >= 1 && p.bendAmt <= PERFORMANCE_DEFAULTS.bendDepth,
          `${where}[${i}]: bend within the depth ceiling`);
        ok(p.bendAt >= 0 && p.bendAt < p.sustain, `${where}[${i}]: bend lands inside the tail`);
      }
    });

    // Chords: one press each, adjacent strings, same instant.
    const tl = buildRiffTimeline(side.rhythm, 1, 2000, side.chordOf);
    side.chordOf.forEach((root, i) => {
      if (root == null) {
        if (i > 0) ok(tl[i].hitAt > tl[i - 1].hitAt, `${where}[${i}]: the riff moves forward`);
        return;
      }
      seen.chord++;
      eq(root, i - 1, `${where}[${i}]: partner immediately follows its root`);
      eq(side.perf[root].hasPartner, true, `${where}[${root}]: root knows it's chorded`);
      eq(side.perf[i].string, side.perf[root].string + 1,
        `${where}[${i}]: adjacent string — one hand can reach both`);
      eq(tl[i].hitAt, tl[root].hitAt, `${where}[${i}]: both gems cross the line together`);
      // A partner never carries its own bend — you're already fretting two.
      eq(side.perf[i].bend, false, `${where}[${i}]: partner doesn't bend`);
    });
  };

  for (let seed = 1; seed <= 120; seed++) {
    const s0 = makeInitialState(config, seed);
    for (const [tier, preset] of Object.entries(RIFF_FALL_DIFFICULTY)) {
      const started = applyAction(s0, riffOffStarted('wildaxe', 'vera',
        { slayer: true, eRush: false, maxLen: preset.maxLen }));
      auditChart(started.battle.atkRiff, `${tier}/s${seed}/atk`);
      auditChart(started.battle.defRiff, `${tier}/s${seed}/def`);

      // Round 2 is not a lesser round. It used to ship bare note arrays with no
      // performance data at all, so sudden death was SIMPLER than the round
      // that forced it.
      const r2 = applyAction(started, riffRound2Started()).battle;
      auditChart(r2.atkRiff, `${tier}/s${seed}/R2atk`);
      auditChart(r2.defRiff, `${tier}/s${seed}/R2def`);
      // Chords must not compound — R2 sizes itself off R1's ROOT count, so the
      // riff can't grow a little longer every round.
      const rootsOf = s => s.chordOf.filter(c => c == null).length;
      eq(rootsOf(r2.atkRiff), rootsOf(started.battle.atkRiff),
        `${tier}/s${seed}: round 2 keeps the tier's riff length`);
    }
  }
}

// ── 3. THE GESTURES ARE ACTUALLY THERE ───────────────────────────────────────
// Structure that exists but never fires teaches nothing. These are deliberately
// loose bounds — they catch "this mechanic is switched off", not tuning.
{
  const pct = k => (100 * seen[k]) / seen.notes;
  ok(pct('sustain') > 15 && pct('sustain') < 45,
    `sustains are a real part of play (got ${pct('sustain').toFixed(1)}%)`);
  ok(pct('bend') > 2, `bends actually occur (got ${pct('bend').toFixed(1)}%)`);
  ok(pct('chord') > 2, `chords actually occur (got ${pct('chord').toFixed(1)}%)`);
  // The melody has to MOVE. An all-"same" chart is a typing test, which is the
  // exact failure the arrow highway was built to replace.
  ok(pct('same') < 55, `the line moves (got ${pct('same').toFixed(1)}% repeats)`);
  ok(seen.up > 0 && seen.down > 0, 'the line goes both ways');
}

console.log(`
charts   ${seen.charts}   notes ${seen.notes}
sustains ${((100 * seen.sustain) / seen.notes).toFixed(1)}%   bends ${((100 * seen.bend) / seen.notes).toFixed(1)}%   chords ${((100 * seen.chord) / seen.notes).toFixed(1)}%
arrows   ↑${seen.up} ↓${seen.down} →${seen.same}

✅ all ${checks} parity assertions passed — the duel asks for what practice teaches`);
