// =============================================================================
// ui/NeonNeck.jsx — 🎯 LANDING-TARGET NECK — the riff-off "riff off" view
// -----------------------------------------------------------------------------
// The third riff-off view (alongside 🎹 piano and 🎸 falling-gem guitar). Notes
// do NOT drop down a highway here. Each note is a RETICLE that appears over the
// exact string/fret cell it lives on in the neon guitar artwork and CLOSES —
// a wide ring shrinking onto a fixed target ring. The instant the two rings
// meet is the instant to play the note. Timing is read as convergence, not as
// distance travelled, so the player's eyes stay on the fretboard.
//
// ⚠️ Ring radius is driven by ONE requestAnimationFrame loop that writes the
// `r` attribute straight from the engine clock (run.startedAt) every frame —
// NOT by CSS animations, for exactly the reason the highway documents: React
// re-renders on every judgment, and restarting a CSS animation's delay does not
// restart the animation, so every reticle would lurch on each re-render. The
// rAF loop reads the clock fresh, so convergence is exact regardless of renders.
//
// GEOMETRY comes from riff/neonNeckGeometry.js, which is GENERATED by measuring
// the artwork (riff/calibrateNeonNeck.mjs). Nothing here is hand-positioned: if
// the art is redrawn, re-run the calibration and every ring follows it.
//
// CAMERA: scale is pinned so the six strings always span the same on-screen
// height, i.e. the camera holds a constant distance from the neck and dollies
// along it. Fret cells narrow toward the body, so more frets come into view up
// there — the way a real camera move looks. It slides only at phrase
// boundaries (CSS transition on the camera <g>), never mid-phrase.
//
// Presentational: run data + results arrive via props; taps route back through
// onPressKey, the same judge the keyboard and the mic use.
// =============================================================================
import { useEffect, useRef } from "react";
import { cellKey, nearestPositionForKey, MAX_FRET, WINDOW } from "../riff/guitarMap.js";
import { FRET_X, WIRE_X, NECK_IMG, stringY, stringPitch, stringSpan } from "../riff/neonNeckGeometry.js";
import neckArt from "../neon_guitar_neck.png";

// ── Stage ───────────────────────────────────────────────────────────────────
// These are viewBox units, not pixels: the SVG stretches to fill whatever width
// its container gives it and this box only fixes the ASPECT RATIO. Make the
// container wider and the whole neck scales up with it, rings included.
const VIEW_W = 1000;
const VIEW_H = 340;

// The six strings always occupy this much of the stage height. Everything else —
// zoom, how many frets you can see — falls out of it. Expressed in viewBox units
// so it stays proportional at any rendered size.
const STRING_SPAN_PX = 200;

// ── Reticle sizing, in multiples of the local string spacing ────────────────
// so rings stay proportional to the neck as it fans out toward the body.
//
// R_TARGET is capped by the TIGHTEST neighbour gap on the neck, because two
// reticles are routinely on screen at once (lead windows overlap). Vertically,
// adjacent strings sit exactly 1.0 string-pitch apart, so a target ring must be
// under 0.5 pitches in radius or same-fret neighbours collide. That is the
// binding constraint — fret cells at the 12th are wider than that. Enforced by
// riff/neonNeck.test.mjs; raise this and the test fails.
const R_TARGET = 0.46;   // the landing ring — where the closing ring lands
const R_OPEN   = 4.20;   // how wide the closing ring starts, a full leadTime out
const R_BURST  = 1.90;   // how far a landed ring flares before it fades
const FADE_IN  = 0.14;   // fraction of leadTime spent fading the reticle in

// ── Neon palette (matches ui/RiffHighway.jsx) ───────────────────────────────
const NEON_CYAN    = '#19e6ff';
const NEON_MAGENTA = '#ff2d95';
const NEON_VIOLET  = '#8a5cff';
const NEON_WHITE   = '#ffffee';

const GRADE_COLORS = { perfect: NEON_WHITE, good: NEON_CYAN, ok: NEON_VIOLET, miss: '#555566', wrong: '#555566' };

// Cyan at the low E blending to magenta at the high e — same order as the
// highway's lanes, so a player switching views keeps their colour vocabulary.
const NEON_STRING_COLORS = [NEON_CYAN, '#33ccff', '#6699ff', NEON_VIOLET, '#cc44dd', NEON_MAGENTA];

const isSharp = k => !!k && k === k.toUpperCase() && k !== k.toLowerCase();
const noteGlyph = k => (isSharp(k) ? `${k}♯` : (k ?? '').toUpperCase());

/**
 * Reticle radius at run-time `now` (ms since run start), in asset units.
 * Closes LINEARLY from R_OPEN to R_TARGET across leadTime — linear on purpose:
 * the shrink rate then reads directly as the passage of time, so a player can
 * judge "how long until it lands" from the ring alone. Holds at R_TARGET once
 * the note is due, through the whole hit window.
 */
function reticleR(now, hitAt, leadTime, pitch) {
  const p = Math.min(1, Math.max(0, (now - (hitAt - leadTime)) / leadTime));
  return (R_OPEN + (R_TARGET - R_OPEN) * p) * pitch;
}

export function NeonNeck({ run, results, ghostHit, accent, onPressKey, showLabels = true }) {
  // Latest run + judged set live on refs so the rAF loop (bound once per run)
  // always reads fresh data without re-subscribing on every judgment.
  const runRef    = useRef(run);
  const judgedRef = useRef({});
  const ringsRef  = useRef(new Map());   // element key → { ring, halo, group, pitch }

  const judged = {};
  (results ?? []).forEach(r => { if (r.noteIdx != null) judged[r.noteIdx] = r; });
  runRef.current    = run;
  judgedRef.current = judged;

  // ── The convergence loop — one rAF per run, attributes written directly. ──
  useEffect(() => {
    if (!run?.notes?.length) return;
    let raf;
    const tick = () => {
      const r = runRef.current;
      if (r) {
        const now = performance.now() - r.startedAt;
        ringsRef.current.forEach((ref) => {
          const { ring, halo, group, pitch } = ref;
          if (!group || !group.isConnected) return;
          const idx   = Number(group.dataset.idx);
          const hitAt = Number(group.dataset.hitat);
          if (judgedRef.current[idx]) { group.style.opacity = '0'; return; } // burst took over
          const lead  = r.leadTime;
          const t     = now - (hitAt - lead);
          if (t < 0) { group.style.opacity = '0'; return; }   // not armed yet
          const p  = Math.min(1, t / lead);
          const rr = reticleR(now, hitAt, lead, pitch);
          ring.setAttribute('r', rr.toFixed(2));
          // Fade in as it arms; once landed, the ring sits on the target and
          // the halo throbs so a note that is DUE RIGHT NOW is unmistakable.
          const past = t - lead;                               // ms past the hit-time
          group.style.opacity = p < FADE_IN ? (p / FADE_IN).toFixed(3) : '1';
          if (halo) {
            const due = past >= -70;
            halo.setAttribute('r', (rr * (due ? 1.55 : 1.22)).toFixed(2));
            halo.style.opacity = due
              ? (0.55 + 0.45 * Math.sin(now / 55)).toFixed(3)
              : (0.10 + 0.35 * p).toFixed(3);
          }
        });
      }
      raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(raf);
  }, [run?.startedAt, run?.notes?.length]); // new run (new turn / round) → fresh loop

  if (!run?.notes?.length) return null;

  // ── Camera — which slice of the neck we are looking at ──────────────────
  // Advances only when every note in the current phrase is judged (the
  // camera-invariant the falling-gem view established: never mid-phrase).
  let anchorFret = 0;
  if (run.anchors?.length) {
    const firstUnjudged = run.notes.find(n => !judged[n.idx]);
    const a = firstUnjudged
      ? (run.anchors.find(x => firstUnjudged.idx >= x.start && firstUnjudged.idx <= x.end) ?? run.anchors[0])
      : run.anchors[run.anchors.length - 1];
    anchorFret = a?.fret ?? 0;
  }
  // Frame the hand window (anchor..anchor+WINDOW) with a fret of air either side.
  const lo = Math.max(0, anchorFret - 1);
  const hi = Math.min(MAX_FRET, anchorFret + WINDOW + 1);

  // The span that must be VISIBLE is the markers plus their rings — not the
  // fret wires. Fret 0's marker sits BEHIND the nut (that is where a player
  // reads an open string), so framing on wires alone pushes it off-stage.
  const edgePad = 12;
  const spanL = FRET_X[lo] - R_TARGET * stringPitch(FRET_X[lo]) - edgePad;
  const spanR = FRET_X[hi] + R_TARGET * stringPitch(FRET_X[hi]) + edgePad;
  let   cx = (spanL + spanR) / 2;

  // Zoom is normally pinned to string height (constant camera distance), but
  // never so far in that the hand window stops fitting — at the nut the frets
  // are wide enough that the window is what binds. Whichever is tighter wins.
  // stringSpan is unsigned: index 0 (low E) is the BOTTOM string, so the raw
  // stringY(5) − stringY(0) is NEGATIVE and would invert the whole camera.
  const k = Math.min(
    STRING_SPAN_PX / stringSpan(cx),
    VIEW_W / (spanR - spanL),
  );
  // Keep the artwork covering the stage — no empty gutters at the neck ends.
  const halfW = VIEW_W / (2 * k);
  cx = NECK_IMG.w <= 2 * halfW ? NECK_IMG.w / 2 : Math.min(Math.max(cx, halfW), NECK_IMG.w - halfW);
  const cy = (stringY(0, cx) + stringY(5, cx)) / 2;
  const tx = VIEW_W / 2 - k * cx;
  const ty = VIEW_H / 2 - k * cy;

  // Text is drawn inside the camera group, so undo the zoom to keep it legible
  // at a constant on-screen size no matter where the camera sits.
  //
  // The FRET NUMBER goes inside the ring (1–2 chars — always fits a target ring
  // ~25px across) and the NOTE LETTER rides above it. They were one string at
  // first, but "A♯12" is four glyphs and simply does not fit inside the ring at
  // any legible size, so it split: fret where your hand goes, letter for the
  // players still reading note names off the keyboard.
  const fretPx  = 12 / k;
  const letterPx = 9 / k;

  const ringRef = (elKey, pitch) => (el) => {
    if (!el) { ringsRef.current.delete(elKey); return; }
    ringsRef.current.set(elKey, {
      group: el,
      ring: el.querySelector('[data-role="ring"]'),
      halo: el.querySelector('[data-role="halo"]'),
      pitch,
    });
  };

  // ── One note's reticle (or its post-judgment burst). ──
  const reticle = (n, key, isGhost) => {
    const pos = isGhost
      ? (nearestPositionForKey(key, n.pos ?? [2, 2]) ?? [0, 0])
      : (n.pos ?? [0, 0]);
    const [sIdx, fret] = pos;
    const x     = FRET_X[Math.max(0, Math.min(MAX_FRET, fret))];
    const y     = stringY(sIdx, x);
    const pitch = stringPitch(x);
    const r     = judged[n.idx];
    const gh    = ghostHit && ghostHit.idx === n.idx ? ghostHit : null;
    const half  = isGhost ? gh?.ghost : gh?.main;   // E-Rush: this half has landed
    const id    = `${n.idx}${isGhost ? 'g' : ''}`;

    // ── Landed / missed → burst on the spot, no travel. ──
    if (r) {
      const col    = GRADE_COLORS[r.grade] ?? accent;
      const isMiss = r.grade === 'miss' || r.grade === 'wrong';
      return (
        <g key={`b${id}-${r.grade}`} style={{ pointerEvents: 'none' }}>
          <circle cx={x} cy={y} r={R_TARGET * pitch} fill="none" stroke={col}
            strokeWidth={isMiss ? 2 : 3} vectorEffect="non-scaling-stroke"
            style={{
              transformOrigin: `${x}px ${y}px`,
              animation: `${isMiss ? 'neonneck-miss' : 'neonneck-land'} 0.45s ease-out forwards`,
              filter: isMiss ? 'none' : `drop-shadow(0 0 6px ${col})`,
            }} />
          {!isMiss && (
            <circle cx={x} cy={y} r={R_TARGET * pitch} fill={col} opacity={0.5}
              style={{
                transformOrigin: `${x}px ${y}px`,
                animation: 'neonneck-flash 0.35s ease-out forwards',
              }} />
          )}
        </g>
      );
    }

    // ── Live reticle ──
    // Ghost (E-Rush) notes read violet; a glitched note reads magenta;
    // otherwise the ring takes its STRING's colour, so the lane is legible
    // before you have even read the fret number.
    const col = half ? NEON_WHITE
      : isGhost ? NEON_VIOLET
      : n.glitched ? NEON_MAGENTA
      : NEON_STRING_COLORS[sIdx];
    const targetR = R_TARGET * pitch;

    return (
      <g key={`r${id}-${key}`} ref={ringRef(`r${id}-${key}`, pitch)}
        data-idx={n.idx} data-hitat={n.hitAt}
        style={{ opacity: 0, pointerEvents: 'none', willChange: 'opacity' }}>
        {/* soft halo — swells and throbs once the note is due */}
        <circle data-role="halo" cx={x} cy={y} r={R_TARGET * pitch} fill="none" stroke={col}
          strokeWidth={6} opacity={0.2} vectorEffect="non-scaling-stroke"
          style={{ filter: `blur(2px)` }} />
        {/* the landing target — fixed, this is what the closing ring lands on */}
        <circle cx={x} cy={y} r={R_TARGET * pitch} fill={`${col}18`} stroke={col}
          strokeWidth={2} strokeDasharray="3 3" opacity={0.85}
          vectorEffect="non-scaling-stroke" />
        {/* the closing ring — rAF shrinks this onto the target */}
        <circle data-role="ring" cx={x} cy={y} r={R_OPEN * pitch} fill="none" stroke={col}
          strokeWidth={2.5} vectorEffect="non-scaling-stroke"
          style={{ filter: `drop-shadow(0 0 4px ${col})` }} />
        {/* fret number — inside the ring, where the hand goes */}
        <text x={x} y={y} textAnchor="middle" dominantBaseline="central"
          fontFamily="'Saira Stencil One',sans-serif" fontSize={fretPx} fontWeight={900}
          fill={NEON_WHITE} style={{ paintOrder: 'stroke' }}
          stroke="#04070f" strokeWidth={fretPx * 0.18}>
          {fret}
        </text>
        {/* Note letter — for players still reading note names. Sits BESIDE the
            ring, not above it: adjacent strings are exactly one string-pitch
            apart and a ring is 0.92 of that across, so there is only a sliver
            of vertical gap and a letter placed above lands on top of the ring
            for the string over it. Sideways there is a whole fret cell of room. */}
        {showLabels && (
          <text x={x + targetR + letterPx * 0.4} y={y} textAnchor="start" dominantBaseline="central"
            fontFamily="'Saira Stencil One',sans-serif" fontSize={letterPx} fontWeight={900}
            fill={col} style={{ paintOrder: 'stroke' }}
            stroke="#04070f" strokeWidth={letterPx * 0.28}>
            {noteGlyph(key)}
          </text>
        )}
      </g>
    );
  };

  return (
    <div style={{ width: '100%', margin: '0 auto' }}>
      <style>{`
        @keyframes neonneck-land  { 0% { transform: scale(1);   opacity: 1; }
                                  100% { transform: scale(${R_BURST}); opacity: 0; } }
        @keyframes neonneck-flash { 0% { transform: scale(0.9); opacity: 0.55; }
                                  100% { transform: scale(1.7); opacity: 0; } }
        @keyframes neonneck-miss  { 0% { transform: scale(1);   opacity: 0.7; }
                                  100% { transform: scale(0.35); opacity: 0; } }
      `}</style>
      <svg viewBox={`0 0 ${VIEW_W} ${VIEW_H}`} width="100%"
        preserveAspectRatio="xMidYMid meet"
        style={{ display: 'block', width: '100%', maxHeight: '68vh',
                 background: '#03060f', borderRadius: 10,
                 border: `1px solid ${NEON_CYAN}22` }}>
        <defs>
          {/* The neck fades out at the stage edges instead of being guillotined.
              ⚠️ These stops MUST be WHITE. An SVG mask is evaluated on LUMINANCE,
              so black stops mean "mask everything out" no matter what opacity
              says — the entire view disappears and all you see is the <svg>
              background. Opacity carries the fade; the colour carries the
              "keep this" signal, and only white means keep. */}
          <linearGradient id="nnFade" x1="0" x2="1">
            <stop offset="0"    stopColor="#fff" stopOpacity="0" />
            <stop offset="0.06" stopColor="#fff" stopOpacity="1" />
            <stop offset="0.94" stopColor="#fff" stopOpacity="1" />
            <stop offset="1"    stopColor="#fff" stopOpacity="0" />
          </linearGradient>
          <mask id="nnMask" maskUnits="userSpaceOnUse"
            x="0" y="0" width={VIEW_W} height={VIEW_H}>
            <rect x="0" y="0" width={VIEW_W} height={VIEW_H} fill="url(#nnFade)" />
          </mask>
        </defs>

        <g mask="url(#nnMask)">
          {/* ── CAMERA — slides only at phrase boundaries ── */}
          <g transform={`translate(${tx.toFixed(2)} ${ty.toFixed(2)}) scale(${k.toFixed(5)})`}
            style={{ transition: 'transform 420ms cubic-bezier(0.4, 0, 0.2, 1)' }}>
            {/* the artwork itself */}
            <image href={neckArt} x={0} y={0} width={NECK_IMG.w} height={NECK_IMG.h} />

            {/* tap targets — every cell on the neck, so the view stays playable
                on touch without a mic. Same judge as keyboard and mic. */}
            {Array.from({ length: 6 }).map((_, s) =>
              Array.from({ length: MAX_FRET + 1 }).map((_, f) => {
                const cxx = FRET_X[f], cyy = stringY(s, cxx), p = stringPitch(cxx);
                const w = (f === 0 ? WIRE_X[0] - FRET_X[0] : (WIRE_X[f] - WIRE_X[f - 1]) / 2) * 1.6;
                return (
                  <rect key={`t${s}-${f}`} x={cxx - w / 2} y={cyy - p / 2} width={w} height={p}
                    fill="transparent" style={{ cursor: 'pointer' }}
                    onPointerDown={e => { e.preventDefault(); onPressKey?.(cellKey(s, f)); }} />
                );
              })
            )}

            {/* reticles — real notes, then E-Rush ghosts on top */}
            {run.notes.map(n => reticle(n, n.key, false))}
            {run.notes.map(n => (n.ghostKey ? reticle(n, n.ghostKey, true) : null))}
          </g>
        </g>
      </svg>
    </div>
  );
}
