import './clientRenderShim.mjs';
import {JSDOM} from 'jsdom';
import {act} from 'react';
import {createRoot} from 'react-dom/client';
import assert from 'node:assert/strict';
import {Game} from '../rlsw-simulator-v3_8_1.jsx';
import {buildTestingGroundsConfig} from '../data/matchSetup.js';
import {HEX_BY_NUM} from '../board/hexMap.js';
import {angleTo,neighborInDirection} from '../board/hexGeometry.js';
const dom=new JSDOM('<div id="root"></div>',{url:'http://localhost/'});
dom.window.Element.prototype.animate=()=>({cancel(){},finished:Promise.resolve()});
for(const name of ['document','HTMLElement','Element','Node','MutationObserver'])Object.defineProperty(globalThis,name,{configurable:true,value:dom.window[name]});
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const config=buildTestingGroundsConfig({beginnerMode:false});config.seed=44;
config.spirits=config.spirits.map(s=>({...s,cpu:false,vibe:100,maxVibe:100}));
const a=HEX_BY_NUM[config.spirits[0].num],b=neighborInDirection(a,0);
config.spirits[0].facing=angleTo(a,b);config.spirits[1].num=b.num;
let state,rollAt=null,damageAt=null;
const root=createRoot(document.getElementById('root'));
const button=text=>[...document.querySelectorAll('button')].find(el=>el.textContent.includes(text));
const click=async el=>{assert.ok(el,'click target');assert.ok(!el.disabled,'enabled');await act(async()=>el.dispatchEvent(new dom.window.MouseEvent('click',{bubbles:true})));};
const wait=async ms=>act(async()=>new Promise(r=>setTimeout(r,ms)));
await act(async()=>root.render(<Game gameState={config} onReturnToLobby={()=>{}} onEngineState={(s,action)=>{
  state=s;if(action.type==='ATTACK_ROLLED')rollAt=performance.now();
  if(action.type==='DAMAGE_APPLIED'&&rollAt)damageAt=performance.now()-rollAt;
}}/>));
await click(button('Continue to Melody'));
for(let i=0;i<3;i++)await click([...document.querySelectorAll('[data-tip-anchor="note-stock"] svg')].map(e=>e.parentElement).find(e=>e.style.cursor==='pointer'));
await click(button('Commit (3 notes'));
await click(button('Swing'));await click(document.querySelector(`[data-hex-num="${b.num}"]`));
assert.ok(state.battle?.swingClash,'live client uses engine clash verdict');
assert.equal(document.querySelector('[data-swing-phase]')?.dataset.swingPhase,'swing_roll');
assert.equal(document.querySelector('[data-board-view]')?.dataset.boardView,'3d');
const before=state.spirits.map(s=>s.vibe),verdict=state.battle;
await wait(7000);
assert.deepEqual(state.spirits.map(s=>s.vibe),before,'no early damage');
assert.equal(document.querySelector('[data-swing-phase]')?.dataset.swingPhase,'swing_charge');
await wait(5500);
assert.ok(!document.querySelector('[data-swing-phase]'),'clash closes');
if(verdict.margin){assert.ok(damageAt>=11000,'damage follows climax');const loser=verdict.attackerWon?verdict.defenderId:verdict.attackerId;
  assert.equal(state.spirits.find(s=>s.id===loser).vibe,100-verdict.margin);}
await act(async()=>root.unmount());
console.log('Mounted Swing journey: board-only phases, frozen verdict, climax timing, exact damage and cleanup passed.');
